#!/usr/bin/env bash
#### Smartpad Specific Tweaks for armbian images
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2023 - till today
#### https://github.com/KwadFan
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces
# Source error handling, leave this in place
set -Ee

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

### Helper func
is_board_type() {
    local board releasefile
    board=""
    releasefile="/etc/armbian-release"
    if [[ -f "${releasefile}" ]]; then
        board="$(grep "BOARD=" "${releasefile}" | cut -d'=' -f2)"
    fi
    echo "${board}"
}

echo_green "Retropie Install..."
sudo apt-get update
echo_green "Dependencies Install for Mupen64Plus"
sudo apt-get install -y libglew-dev libfreetype6-dev libaudiofile-dev libpng-dev libz-dev libsdl2-dev
pushd "/home/${BASE_USER}" &>/dev/null
echo_green "git clone Retropie-smartpi"
git clone https://github.com/Yumi-Lab/Retropie-smartpi.git
cd Retropie-smartpi
sudo chmod +x retropie_setup.sh
sudo chmod +x SambaRetropie.sh
sudo chmod +x retropie_packages.sh
sudo chmod +x autostartES.sh
sudo __debug=1 ./retropie_packages.sh setup basic_install
#sudo ./retropie_packages.sh bluetooth depends
#sudo ./retropie_packages.sh usbromservice
#sudo ./retropie_packages.sh samba depends
#sudo ./retropie_packages.sh samba install_shares
#sudo ./autostartES.sh
#sudo chmod 777 -R /opt/retropie/
#sudo chmod +x /opt/retropie/configs/all/autostart.sh
cd ..
popd &>/dev/null

echo_green "Install Retropie ... [DONE]"



### Install plymouth theme and install yumi Plymouth repository
echo_green "Install Yumi Lab Plymouth theme on SmartPad..."

smartpad_install_theme() {
    local src dest
    dest="/usr/share/plymouth/themes/"
    src="/home/${BASE_USER}/$(basename "${SMARTPAD_PLYMOUTH_REPO/.git/}")"
    src="${src}/pack_2/hexagon_alt"
    if [[ -d "${src}" ]]; then
        sudo cp -vr "${src}" "${dest}"
    fi
    echo_green "Set default theme to ${SMARTPAD_PLYMOUTH_THEME} ..."
    sudo plymouth-set-default-theme "${SMARTPAD_PLYMOUTH_THEME}"
}

pushd "/home/${BASE_USER}" &>/dev/null
sudo -u "${BASE_USER}" git clone "${SMARTPAD_PLYMOUTH_REPO}"
smartpad_install_theme
popd &>/dev/null

echo_green "Install Yumi Lab Plymouth theme on SmartPad... [DONE]"

